import type { Decorator, Preview } from "@storybook/svelte-vite";

// Must run before any story module evaluates: sets window.env so config-reading components import.
import "./preview-env";
import "../src/front/style/index.css";
import type { Locales } from "../src/i18n/i18n-types";
import { loadLocale } from "../src/i18n/i18n-util.sync";
import { setLocale } from "../src/i18n/i18n-svelte";

// Without this, every component that reads `$LL` throws in isolation. Initialise the default
// locale at module load so even module-level translation reads resolve, then let the toolbar
// decorator below switch it per story. The `i18n-*` files are generated by `npm run typesafe-i18n`
// (the Storybook CI job runs it before the tests).
const DEFAULT_LOCALE: Locales = "en-US";
loadLocale(DEFAULT_LOCALE);
setLocale(DEFAULT_LOCALE);

const withLocale: Decorator = (story, context) => {
    const locale = (context.globals.locale as Locales | undefined) ?? DEFAULT_LOCALE;
    loadLocale(locale);
    setLocale(locale);
    return story();
};

const preview: Preview = {
    parameters: {
        controls: {
            matchers: {
                color: /(background|color)$/i,
                date: /Date$/i,
            },
        },

        // The app is a dark UI: default the canvas to dark so light-on-dark components
        // (the whole design system) render on a realistic surface.
        backgrounds: {
            options: {
                dark: { name: "Dark", value: "#14161c" },
                light: { name: "Light", value: "#ffffff" },
            },
        },

        // WorkAdventure UI ships both full-screen and embedded in narrow side panels;
        // expose those sizes so overlays and menus can be checked where they actually run.
        viewport: {
            options: {
                embedded: { name: "Embedded panel", styles: { width: "420px", height: "720px" } },
                mobile: { name: "Mobile", styles: { width: "375px", height: "812px" } },
                desktop: { name: "Desktop", styles: { width: "1280px", height: "800px" } },
            },
        },

        a11y: {
            // 'todo' - show a11y violations in the test UI only
            // 'error' - fail CI on a11y violations
            // 'off' - skip a11y checks entirely
            test: "todo",
        },
    },

    decorators: [withLocale],

    globalTypes: {
        locale: {
            description: "Active i18n locale",
            toolbar: {
                icon: "globe",
                items: [
                    { value: "en-US", title: "English" },
                    { value: "fr-FR", title: "Français" },
                ],
                dynamicTitle: true,
            },
        },
    },

    initialGlobals: {
        backgrounds: { value: "dark" },
        locale: DEFAULT_LOCALE,
    },
};

export default preview;
