// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en-US'

export type Locales =
	| 'en-US'
	| 'fr-FR'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * Users
	 */
	users: string
	userList: {
		/**
		 * Disconnected
		 */
		disconnected: string
		/**
		 * Is on thi map !
		 */
		isHere: string
		/**
		 * Is on another map !
		 */
		isOverThere: string
		/**
		 * Teleport
		 */
		teleport: string
		/**
		 * Just look it up!
		 */
		search: string
		/**
		 * Walk to
		 */
		walkTo: string
		/**
		 * Teleporting ...
		 */
		teleporting: string
	}
	/**
	 * Connection to presence server ...
	 */
	reconnecting: string
	/**
	 * Waiting user data ...
	 */
	waitingData: string
	/**
	 * Search for user, message, channel, etc.
	 */
	search: string
	/**
	 * Invite
	 */
	invite: string
	/**
	 * This room is empty, invite a colleague or friend to join you!
	 */
	roomEmpty: string
}

export type TranslationFunctions = {
	/**
	 * Users
	 */
	users: () => LocalizedString
	userList: {
		/**
		 * Disconnected
		 */
		disconnected: () => LocalizedString
		/**
		 * Is on thi map !
		 */
		isHere: () => LocalizedString
		/**
		 * Is on another map !
		 */
		isOverThere: () => LocalizedString
		/**
		 * Teleport
		 */
		teleport: () => LocalizedString
		/**
		 * Just look it up!
		 */
		search: () => LocalizedString
		/**
		 * Walk to
		 */
		walkTo: () => LocalizedString
		/**
		 * Teleporting ...
		 */
		teleporting: () => LocalizedString
	}
	/**
	 * Connection to presence server ...
	 */
	reconnecting: () => LocalizedString
	/**
	 * Waiting user data ...
	 */
	waitingData: () => LocalizedString
	/**
	 * Search for user, message, channel, etc.
	 */
	search: () => LocalizedString
	/**
	 * Invite
	 */
	invite: () => LocalizedString
	/**
	 * This room is empty, invite a colleague or friend to join you!
	 */
	roomEmpty: () => LocalizedString
}

export type Formatters = {}
