import {expect, test} from '@playwright/test';
import { login } from './utils/roles';
import {publicTestMapUrl} from "./utils/urls";
import { evaluateScript } from './utils/scripting';

test.describe('Scripting player message function', () => {
    test('play text on the head of user', async ({ page, browser}, { project }) => {
        await page.goto(
            publicTestMapUrl("tests/E2E/empty.json", "scripting_follow")
        );

        await login(page);

        let playerMessage;
        
        // Test to displaye text message on the head of user
        await evaluateScript(page, async () => {
            playerMessage = WA.ui.displayPlayerMessage({
                message:"Hello world 👋",
            });
        });

        // Test if the DomElement generated by the character is visible
        await expect(page.locator("span.characterTriggerAction")).toBeVisible();

        // Test to remove message
        await evaluateScript(page, async () => {
            playerMessage?.remove();
        });

        // Test if the DomElement generated by the character is visible
        await expect(page.locator("span.characterTriggerAction")).toBeHidden();
    });
});
