{{- if and .Values.gateway.enabled .Values.singleDomain -}}
{{- $fullName := include "workadventure.fullname" . -}}
{{- $gatewayName := .Values.gateway.gatewayName | default (printf "%s-gateway" $fullName) -}}
{{- $gatewayNamespace := .Values.gateway.gatewayNamespace | default .Release.Namespace -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}-root
  labels:
    {{- include "workadventure.labels" . | nindent 4 }}
    {{- with .Values.gateway.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
  - name: {{ $gatewayName }}
    {{- if ne $gatewayNamespace .Release.Namespace }}
    namespace: {{ $gatewayNamespace }}
    {{- end }}
  hostnames:
  - {{ .Values.domainName | quote }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /ws/
    backendRefs:
    - name: {{ include "workadventure.fullname" . }}-play
      port: {{ .Values.play.service.wsPort }}
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ include "workadventure.fullname" . }}-play
      port: {{ .Values.play.service.port }}
{{- end }}