{{- if and (or .Values.gateway.enabled .Values.icon.gateway.enabled) (not .Values.singleDomain) -}}
{{- $fullName := include "workadventure.fullname" . -}}
{{- $gatewayName := .Values.gateway.gatewayName | default (printf "%s-gateway" $fullName) -}}
{{- $gatewayNamespace := .Values.gateway.gatewayNamespace | default .Release.Namespace -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}-icon
  labels:
    {{- include "workadventure.labels" . | nindent 4 }}
    {{- with .Values.icon.gateway.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.gateway.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with (merge .Values.icon.gateway.annotations .Values.gateway.annotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
  - name: {{ $gatewayName }}
    {{- if ne $gatewayNamespace .Release.Namespace }}
    namespace: {{ $gatewayNamespace }}
    {{- end }}
  hostnames:
  - {{ (include "workadventure.iconDomainName" .) | quote }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ include "workadventure.fullname" . }}-icon
      port: {{ .Values.icon.service.port }}
{{- end }}