{{- if .Values.livekitServer.enabled }}

{{- $livekitSecretKey := (randAlpha 32) | b64enc }}

{{- $secret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-secret-env-livekit" (include "workadventure.fullname" .))) }}

{{- if $secret }}
{{- $livekitSecretKey = coalesce (index $secret.data "LIVEKIT_API_SECRET") $livekitSecretKey }}
{{- end }}

---
# This secret is meant to be used by the back server of WorkAdventure
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "workadventure.fullname" . }}-secret-env-livekit
  labels:
    {{- include "workadventure.labels" . | nindent 4 }}
type: Opaque
data:
  LIVEKIT_API_KEY: "livekit_workadventure_key"
: {{ $livekitSecretKey | quote }}


---
# This secret is adapted to be readable by the Livekit deployment

apiVersion: v1
kind: Secret
metadata:
  name: livekit-keys-secret
  labels:
    {{- include "workadventure.labels" . | nindent 4 }}
data:
  {{ .Values.livekitServer.livekit.key_file }}: {{ toYaml ( dict "livekit_workadventure_key" $livekitSecretKey ) | b64enc }}

{{- end }}
