{{- if and (or .Values.gateway.enabled .Values.play.gateway.enabled) (not .Values.singleDomain) -}}
{{- $fullName := include "workadventure.fullname" . -}}
{{- $gatewayName := .Values.gateway.gatewayName | default (printf "%s-gateway" $fullName) -}}
{{- $gatewayNamespace := .Values.gateway.gatewayNamespace | default .Release.Namespace -}}
---
# HTTPRoute for play domain
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}-play-front
  labels:
    {{- include "workadventure.labels" . | nindent 4 }}
    {{- with .Values.play.gateway.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.gateway.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with (merge .Values.play.gateway.annotations .Values.gateway.annotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
  - name: {{ $gatewayName }}
    {{- if ne $gatewayNamespace .Release.Namespace }}
    namespace: {{ $gatewayNamespace }}
    {{- end }}
  hostnames:
  - {{ (include "workadventure.playDomainName" .) | quote }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ include "workadventure.fullname" . }}-play
      port: {{ .Values.play.service.port }}
---
# HTTPRoute for pusher domain
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}-play-pusher
  labels:
    {{- include "workadventure.labels" . | nindent 4 }}
    {{- with .Values.play.gateway.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.gateway.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with (merge .Values.play.gateway.annotations .Values.gateway.annotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
  - name: {{ $gatewayName }}
    {{- if ne $gatewayNamespace .Release.Namespace }}
    namespace: {{ $gatewayNamespace }}
    {{- end }}
  hostnames:
  - {{ (include "workadventure.pusherDomainName" .) | quote }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /ws/
    backendRefs:
    - name: {{ include "workadventure.fullname" . }}-play
      port: {{ .Values.play.service.wsPort }}
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ include "workadventure.fullname" . }}-play
      port: {{ .Values.play.service.port }}
{{- if and .Values.play.gateway.roomApiEnabled (or .Values.gateway.enabled .Values.play.gateway.enabled) }}
---
# HTTPRoute for room-api domain
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}-play-roomapi
  labels:
    {{- include "workadventure.labels" . | nindent 4 }}
    {{- with .Values.play.gateway.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.gateway.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with (merge .Values.play.gateway.annotations .Values.gateway.annotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
  - name: {{ $gatewayName }}
    {{- if ne $gatewayNamespace .Release.Namespace }}
    namespace: {{ $gatewayNamespace }}
    {{- end }}
  hostnames:
  - {{ (include "workadventure.roomApiDomainName" .) | quote }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ include "workadventure.fullname" . }}-room-api
      port: {{ .Values.play.roomApiService.port }}
{{- end }}
{{- end }}