---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "workadventure.fullname" . }}-env-play
  labels:
    {{- include "workadventure.labels" . | nindent 4 }}
data:
  API_URL: {{ range $replica, $f := until (int .Values.back.replicaCount) }}{{ include "workadventure.fullname" $ }}-back-{{ $replica }}:50051{{ if ne $replica (sub (int $.Values.back.replicaCount) 1)  }}{{ "," }}{{ end }}{{ end }}
  ICON_URL: {{ include "workadventure.iconUrl" . | quote }}
  UPLOADER_URL: {{ include "workadventure.uploaderUrl" . | quote }}
  PUSHER_URL: {{ include "workadventure.pusherUrl" . | quote }}
  FRONT_URL: {{ include "workadventure.playUrl" . | quote }}
  # The PUBLIC_MAP_STORAGE_URL is only used when no admin is connected
  PUBLIC_MAP_STORAGE_URL: {{ include "workadventure.mapStorageUrl" . | quote }}
  INTERNAL_MAP_STORAGE_URL: "http://{{ include "workadventure.fullname" . }}-mapstorage:3000"
  ENABLE_OPENAPI_ENDPOINT: "true"
  ROOM_API_PORT: "50051"
  MAP_STORAGE_PATH_PREFIX: "{{ if .Values.singleDomain }}/map-storage{{ else }}/{{ end }}"
  {{- if not .Values.play.env.ALLOWED_CORS_ORIGIN }}
  ALLOWED_CORS_ORIGIN: {{ include "workadventure.playUrl" . | quote }}
  {{- end}}

  {{- range $key, $val := .Values.commonEnv }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}

  {{- range $key, $val := .Values.play.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
