#!/bin/bash
. "$(dirname "$0")/_/husky.sh"

# Vérifier la complétude des traductions
check_translations() {
  cd play || exit 1
  npm run i18n:check
}

(
cd messages || exit
npm run precommit
)
(
cd play || exit
npm run precommit
)
(
check_translations
)
(
cd back || exit
npm run precommit
)
(
cd map-storage || exit
npm run precommit
)
(
cd tests || exit
npm run precommit
)
(
cd libs/map-editor || exit
npm run precommit
)
(
cd libs/shared-utils || exit
npm run precommit
)
(
cd libs/store-utils || exit
npm run precommit
)
(
cd contrib/tools/generate-env-docs || exit
npm run generate
)
