{{- $name := include "workadventure.pusher.name" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    {{- include "workadventure.labels" . | nindent 4 }}
spec:
  type: {{ .Values.pusher.service.type }}
  ports:
    - port: {{ .Values.pusher.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "workadventure.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/type: "{{ .Values.pusher.name }}"
