import { describe, expect, it } from "vitest";
import { sanitizeHtml } from "../../../src/front/Utils/HtmlSanitizer";

// Markup produced by the keyboard badges of SpeechDomElement.
const SPACE_BADGE_HTML =
    '<span class="speech-key speech-key--space" aria-hidden="true">' +
    '<svg width="48" height="18" viewBox="0 0 48 18" class="speech-key__svg" style="vertical-align: middle;">' +
    '<defs><filter id="speech-key-space-shadow-1" x="-20%" y="-20%" width="140%" height="140%">' +
    '<feDropShadow dx="0" dy="1" stdDeviation="0.8" flood-opacity="0.35"></feDropShadow></filter></defs>' +
    '<rect x="0.5" y="0.5" width="47" height="17" rx="4" fill="#f8fafc" stroke="#cbd5e1" stroke-width="1" ' +
    'filter="url(#speech-key-space-shadow-1)"></rect>' +
    '<text x="24" y="12" text-anchor="middle" font-size="7" fill="#0f172a">SPACE</text></svg></span>';

describe("HtmlSanitizer", () => {
    it("keeps the markup generated for the speech bubble keyboard badges", () => {
        const sanitized = sanitizeHtml(SPACE_BADGE_HTML);

        expect(sanitized).toContain("speech-key--space");
        expect(sanitized).toContain("<svg");
        expect(sanitized).toContain("<rect");
        expect(sanitized).toContain("<filter");
        // Case-insensitive: unlike browsers, jsdom lowercases the name of the SVG elements it parses.
        expect(sanitized).toMatch(/<fedropshadow/i);
        expect(sanitized).toContain('filter="url(#speech-key-space-shadow-1)"');
        expect(sanitized).toContain("SPACE");
    });

    it("keeps the markup generated by the Markdown renderer", () => {
        const sanitized = sanitizeHtml('<p>Hello <strong>world</strong> <a href="https://example.com">link</a></p>');

        expect(sanitized).toContain("<strong>world</strong>");
        expect(sanitized).toContain('href="https://example.com"');
    });

    it("removes scripts and event handlers", () => {
        expect(sanitizeHtml('<img src="x" onerror="alert(1)">')).not.toContain("onerror");
        expect(sanitizeHtml("<script>alert(1)</script>")).not.toContain("alert(1)");
        expect(sanitizeHtml("<svg><script>alert(1)</script></svg>")).not.toContain("alert(1)");
        expect(sanitizeHtml('<a href="javascript:alert(1)">click</a>')).not.toContain("javascript:");
    });
});
